Config innlasting/ codePipeline
BIBSYSDEV/alma-description-updater pull request #73
Opened 2021-09-06 12:12 UTC by gregorgabriel

refactoring angående innlasting av Config 
endring til CodePipleine for dependabot

2021-09-07 09:54 UTC, anetteOlli approved these changes

2021-09-07 11:51 UTC, nraanes commented on pipeline.yml
> +    GitHubOwner:
For mye innrykk

2021-09-07 11:52 UTC, nraanes commented on pipeline.yml
>                  Provider: CodeStarSourceConnection
Provider: GitHub

2021-09-07 11:54 UTC, nraanes requested changes
Se kommentarer

2021-09-08 06:33 UTC, gregorgabriel commented on pipeline.yml
> +    GitHubOwner:
Sorry, I dont see it:
`  GitHubOAuthToken:
    Description: OAuth token used by AWS CodePipeline to connect to GitHub
    NoEcho: true
    Type: String
    Default: '{{resolve:secretsmanager:githubtoken:SecretString}}'
    GitHubOwner:
      Description: GitHub username owning the repo
      Type: String
      Default: BIBSYSDEV
  GitRepo:`

2021-09-08 06:34 UTC, gregorgabriel commented on pipeline.yml
> +    GitHubOwner:
you are right

2021-09-08 06:36 UTC, merged